Switching to use my fork w/o the copter integration.
This is breaking the arbiter.

Exception in thread Thread-10:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
      self.run()
        File "/usr/lib/python3.5/threading.py", line 862, in run
            self._target(*self._args, **self._kwargs)
              File "/opt/sasc/venv3/lib/python3.5/site-packages/acs_lib-0.1.0-py3.5.egg/acs_lib/acs_network/acs_network_ground.py", line 159, in read_socket
                  self.__msg_rcvd_cb(msg)
                    File "/opt/sasc/venv3/lib/python3.5/site-packages/arbiter-0.1.1-py3.5.egg/arbiter/arbiter_state.py", line 119, in on_red_message_received
                        self.red_swarm_snapshot.process_msg(msg)
                          File "/opt/sasc/venv3/lib/python3.5/site-packages/arbiter-0.1.1-py3.5.egg/arbiter/swarm_snapshot/__init__.py", line 32, in process_msg
                              self.__states[id] = ACS_UAVState(id)
                                File "/opt/sasc/venv3/lib/python3.5/site-packages/acs_lib-0.1.0-py3.5.egg/acs_lib/acs_uav_state.py", line 71, in __init__
                                    self.__vehicle_type = enums.AC_UNKNOWN
                                    AttributeError: module 'ap_lib.ap_enumerations' has no attribute 'AC_UNKNOWN'

^CTraceback (most recent call last):
  File "/opt/sasc/venv3/lib/python3.5/site-packages/arbiter-0.1.1-py3.5.egg/arbiter/arbiter_gui/__init__.py", line 75, in update_frequent
  KeyboardInterrupt